### PR TITLE
fix: style fixing. Modify defaults

### LINKED ISSUE #57: Style issues on girlsintech.org
1. The default options feels like there is one missing - either let's add a fourth option $500 or make each option full-width same as when there are names for the different levels of support.
2. Scrolling feels quite strange, kinda like i'm still on the other page. There should be no scrollbar at all since everything can fit on my screen.

image

### LINKED ISSUE #69: Make sure the widget fits in the viewport
Ideally, the entire widget should be displayed in the viewport in desktop.

Examples of how it's displaying currently:

The top of the widget is obscured
image

There shouldn't be a scrollbar. Viewport: 1536 × 722 px
image

 Would be worth checking other screen size variations too, to see how well it displays across the board.

### PR DESCRIPTION
**Pull request by martinbianchi**
closes #57
closes #69 

- widget overflow stylings. 
- disable page body overflow when widget is open. 
- modify defaults

### CODE REVIEW

File: src/defaultOptions.js [hunk 1]
```diff
@@ -58,12 +62,10 @@ const everyMonthOptions = {
...
           'Monthly gifts help us focus on our mission and long-term impact',
         levels: [
-          { amount: '5' },
-          { amount: '10' },
-          { amount: '20' },
+          { amount: '25' },
           { amount: '50' },
           { amount: '100' },
-          { amount: '200' },
+          { amount: '500' },
```
Comment (markulrich) [inline src/defaultOptions.js:68]: Are these for the monthly donation levels? A bit confused as to why they are under `en` section and why this code does not match the existing 25/50/100 options, do they need to be repeated twice could we remove this section?

File: src/defaultOptions.js [hunk 2]
```diff
@@ -29,6 +29,10 @@ const everyMonthOptions = {
         amount: '100',
         bgColor: '#A0CBFE',
       },
+      {
+        amount: '500',
```
Comment (markulrich) [inline src/defaultOptions.js:33]:
```suggestion
        amount: '200',
```
I like 200/month as the largest, 500/month feels a bit much ...

File: src/defaultOptions.js [hunk 3]
```diff
@@ -29,6 +29,10 @@ const everyMonthOptions = {
...
+        bgColor: '#A0CBFE',
```
Comment (markulrich) [inline src/defaultOptions.js:34]: Is this `bgColor` used, could we remove it?

File: src/defaultOptions.js (hunk 1 above)
Comment (osdiab) [reply src/defaultOptions.js:68]: I agree that it's confusing, we should make another pass at the options format in a major version. the way it is now is counterintuitive, if you don't provide everything in i18n then it'll just null dereference and crash, it's an emergent property of how the design evolved; we can streamline the format a lot but for now just to get this going let's go with it

Comment (martinbianchi) [reply src/defaultOptions.js:68]: Inside `monthly` we have the generic and common part of the config. Inside `i18n` we have the labels and descriptions that corresponds to each language. The amount prop act as a key to link them.  
For the minimum default values, isn't neccessary anymore provide texts, so they seems useless at this point

File: src/defaultOptions.js (hunk 3 above)
Comment (martinbianchi) [reply src/defaultOptions.js:34]: No, we are not using them after #29. I'll remove them

File: src/defaultOptions.js (hunk 1 above)
Comment (osdiab) [reply src/defaultOptions.js]: I'll make a proposal later but basically I think we shouldn't be using amounts as an ID and then having to ad-hoc make sure they're matching each other in separate parts of the config; I'd rather that everything related to an amount is centralized in one place, and anywhere where you can config a string, you can alternatively provide an object from language code to string values. That way the only thing you need to correlate are the language codes, and that's much easier to sanity check, all the info would be in one place. After #74 is good to go this can be expressed simply as a type.

Comment (osdiab) [reply src/defaultOptions.js]: but yea doens't need to block this

File: src/components/Button/button.css [hunk 4]
```diff
@@ -25,7 +25,7 @@
     background-color: rgb(0, 139, 109);
 }
 
-@media only screen and (max-width: 64em) {
+@media only screen and (max-width: 64em), (max-height: 46.3125em)  {
```
Comment (osdiab) [inline src/components/Button/button.css:28]: This kind of media query seems really brittle, but we can improve on this later.

**Review by osdiab — APPROVED** [review]

File: src/components/Button/button.css (hunk 4 above)
Comment (martinbianchi) [reply src/components/Button/button.css:28]: I agree with you in the point of the max-height media query is not the best one, I do it because the widget is large and in some screens, like for example 1550x722 the widget doesn't fit on the screen.

Regarding the choice of `em` for media-queries which alternative do you think is best? I think that is the best and the most consistent unit to use in media queries

Comment (osdiab) [reply src/components/Button/button.css:28]: Ah I was misinformed about the em unit in the context of media queries, I think it's fine here (but probably not that necessary on modern browsers)! But yeah the more we can get the styles can naturally scale to the browser dimensions without needing to corner case various screen sizes, the better IMO.
